CREATE DATABASE IF NOT EXISTS photoprism;
CREATE DATABASE IF NOT EXISTS paperless;

CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'test123';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
